/**
 * JavaScript and Node.js SDK for OpenFGA
 *
 * API version: 1.x
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://openfga.dev/community
 * License: [Apache-2.0](https://github.com/openfga/js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */


import { TelemetryCounters } from "../../telemetry/counters";

describe("TelemetryCounters", () => {
  test("should have correct counter details", () => {
    expect(TelemetryCounters.credentialsRequest.name).toBe("fga-client.credentials.request");
    expect(TelemetryCounters.credentialsRequest.unit).toBe("milliseconds");
    expect(TelemetryCounters.credentialsRequest.description).toBe("The number of times an access token is requested.");
  });
});
