/**
 * JavaScript and Node.js SDK for OpenFGA
 *
 * API version: 1.x
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://openfga.dev/community
 * License: [Apache-2.0](https://github.com/openfga/js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */


import { TelemetryHistograms } from "../../telemetry/histograms";

describe("TelemetryHistograms", () => {
  test("should have correct histogram details for request duration", () => {
    expect(TelemetryHistograms.requestDuration.name).toBe("fga-client.request.duration");
    expect(TelemetryHistograms.requestDuration.unit).toBe("milliseconds");
    expect(TelemetryHistograms.requestDuration.description).toBe("How long it took for a request to be fulfilled.");
  });

  test("should have correct histogram details for query duration", () => {
    expect(TelemetryHistograms.queryDuration.name).toBe("fga-client.query.duration");
    expect(TelemetryHistograms.queryDuration.unit).toBe("milliseconds");
    expect(TelemetryHistograms.queryDuration.description).toBe("How long it took to perform a query request.");
  });
});
