/**
 * JavaScript and Node.js SDK for OpenFGA
 *
 * API version: 1.x
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://openfga.dev/community
 * License: [Apache-2.0](https://github.com/openfga/js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */


/**
 * Version of the OpenFGA JavaScript SDK.
 */
const SdkVersion = "0.9.3";

/**
 * User agent used in HTTP requests.
 */
const UserAgent = "openfga-sdk js/0.9.3";

/**
 * Example API domain for documentation/tests.
 */
const SampleBaseDomain = "fga.example";

/**
 * API URL used for tests.
 */
const TestApiUrl = `https://api.${SampleBaseDomain}`;

/**
 * API Token Issuer URL used for tests.
 */
const TestIssuerUrl = `https://issuer.${SampleBaseDomain}`;

/**
 * Default API URL.
 */
const DefaultApiUrl = "http://localhost:8080";

// Retry configuration

/**
 * Maximum allowed number of retries for HTTP requests.
 */
const RetryMaxAllowedNumber = 15;

/**
 * Default maximum number of retries for HTTP requests.
 */
const DefaultMaxRetry = 3;

/**
 * Default minimum wait time between retries in milliseconds.
 */
const DefaultMinWaitInMs = 100;

/**
 * Maximum backoff time in seconds.
 */
const MaxBackoffTimeInSec = 120;

/**
 * Maximum allowable duration for retry headers in seconds.
 */
const RetryHeaderMaxAllowableDurationInSec = 1800;

/**
 * Standard HTTP header for retry-after.
 */
const RetryAfterHeaderName = "Retry-After";

/**
 * Rate limit reset header name.
 */
const RateLimitResetHeaderName = "X-RateLimit-Reset";

/**
 * Alternative rate limit reset header name.
 */
const RateLimitResetAltHeaderName = "X-Rate-Limit-Reset";

// Client methods

/**
 * Maximum number of parallel requests for a single method.
 */
const ClientMaxMethodParallelRequests = 10;

/**
 * Maximum batch size for batch requests.
 */
const ClientMaxBatchSize = 50;

/**
 * Header used to identify the client method.
 */
const ClientMethodHeader = "X-OpenFGA-Client-Method";

/**
 * Header used to identify bulk requests.
 */
const ClientBulkRequestIdHeader = "X-OpenFGA-Client-Bulk-Request-Id";

// Connection options

/**
 * Default timeout for HTTP requests in milliseconds.
 */
const DefaultRequestTimeoutInMs = 10000;

/**
 * Default connection timeout in milliseconds.
 */
const DefaultConnectionTimeoutInMs = 10000;

// Token management

/**
 * Buffer time in seconds before token expiry to consider it expired.
 */
const TokenExpiryThresholdBufferInSec = 300;

/**
 * Jitter time in seconds to add randomness to token expiry checks.
 */
const TokenExpiryJitterInSec = 300;

// FGA Response Headers

/**
 * Response header name for query duration in milliseconds.
 */
const QueryDurationHeaderName = "fga-query-duration-ms";

const SdkConstants = Object.freeze({
  SdkVersion,
  UserAgent,
  SampleBaseDomain,
  TestApiUrl,
  TestIssuerUrl,
  DefaultApiUrl,
  RetryMaxAllowedNumber,
  DefaultMaxRetry,
  DefaultMinWaitInMs,
  MaxBackoffTimeInSec,
  RetryHeaderMaxAllowableDurationInSec,
  RetryAfterHeaderName,
  RateLimitResetHeaderName,
  RateLimitResetAltHeaderName,
  ClientMaxMethodParallelRequests,
  ClientMaxBatchSize,
  ClientMethodHeader,
  ClientBulkRequestIdHeader,
  DefaultRequestTimeoutInMs,
  DefaultConnectionTimeoutInMs,
  TokenExpiryThresholdBufferInSec,
  TokenExpiryJitterInSec,
  QueryDurationHeaderName,
});

export default SdkConstants;