repos:
- repo: https://github.com/gitleaks/gitleaks
  rev: v8.16.3
  hooks:
  - id: gitleaks
- repo: local
  hooks:
  - id: eslint
    name: eslint
    entry: npx eslint
    language: system
    types_or: [javascript, ts, tsx]
    pass_filenames: true
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
