"use strict";
/**
 * JavaScript and Node.js SDK for OpenFGA
 *
 * API version: 1.x
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://openfga.dev/community
 * License: [Apache-2.0](https://github.com/openfga/js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.TelemetryHistograms = void 0;
class TelemetryHistograms {
}
exports.TelemetryHistograms = TelemetryHistograms;
TelemetryHistograms.requestDuration = {
    name: "fga-client.request.duration",
    unit: "milliseconds",
    description: "How long it took for a request to be fulfilled.",
};
TelemetryHistograms.queryDuration = {
    name: "fga-client.query.duration",
    unit: "milliseconds",
    description: "How long it took to perform a query request.",
};
TelemetryHistograms.httpRequestDuration = {
    name: "fga-client.http_request.duration",
    unit: "milliseconds",
    description: "The time (in milliseconds) for a single HTTP request to complete.",
};
//# sourceMappingURL=histograms.js.map