"use strict";
/**
 * JavaScript and Node.js SDK for OpenFGA
 *
 * API version: 1.x
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://openfga.dev/community
 * License: [Apache-2.0](https://github.com/openfga/js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */
var __createBinding = (this && this.__createBinding) || (Object.create ? (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    var desc = Object.getOwnPropertyDescriptor(m, k);
    if (!desc || ("get" in desc ? !m.__esModule : desc.writable || desc.configurable)) {
      desc = { enumerable: true, get: function() { return m[k]; } };
    }
    Object.defineProperty(o, k2, desc);
}) : (function(o, m, k, k2) {
    if (k2 === undefined) k2 = k;
    o[k2] = m[k];
}));
var __setModuleDefault = (this && this.__setModuleDefault) || (Object.create ? (function(o, v) {
    Object.defineProperty(o, "default", { enumerable: true, value: v });
}) : function(o, v) {
    o["default"] = v;
});
var __importStar = (this && this.__importStar) || (function () {
    var ownKeys = function(o) {
        ownKeys = Object.getOwnPropertyNames || function (o) {
            var ar = [];
            for (var k in o) if (Object.prototype.hasOwnProperty.call(o, k)) ar[ar.length] = k;
            return ar;
        };
        return ownKeys(o);
    };
    return function (mod) {
        if (mod && mod.__esModule) return mod;
        var result = {};
        if (mod != null) for (var k = ownKeys(mod), i = 0; i < k.length; i++) if (k[i] !== "default") __createBinding(result, mod, k[i]);
        __setModuleDefault(result, mod);
        return result;
    };
})();
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.Credentials = exports.DEFAULT_TOKEN_ENDPOINT_PATH = void 0;
const axios_1 = __importDefault(require("axios"));
const jose = __importStar(require("jose"));
const validation_1 = require("../validation");
const errors_1 = require("../errors");
const common_1 = require("../common");
const types_1 = require("./types");
const attributes_1 = require("../telemetry/attributes");
const counters_1 = require("../telemetry/counters");
const crypto_1 = require("crypto");
const constants_1 = __importDefault(require("../constants"));
const HTTP_SCHEME = "http://";
const HTTPS_SCHEME = "https://";
exports.DEFAULT_TOKEN_ENDPOINT_PATH = "oauth/token";
class Credentials {
    static init(configuration, axios = axios_1.default) {
        return new Credentials(configuration.credentials, axios, configuration.telemetry, configuration.baseOptions);
    }
    constructor(authConfig, axios = axios_1.default, telemetryConfig, baseOptions) {
        this.authConfig = authConfig;
        this.axios = axios;
        this.telemetryConfig = telemetryConfig;
        this.baseOptions = baseOptions;
        this.accessTokenExpiryBufferInMs = 0;
        this.initConfig();
        this.isValid();
    }
    /**
     * Sets the default config values
     * @private
     */
    initConfig() {
        switch (this.authConfig?.method) {
            case types_1.CredentialsMethod.ApiToken:
                if (this.authConfig.config) {
                    if (!this.authConfig.config.headerName) {
                        this.authConfig.config.headerName = "Authorization";
                    }
                    if (!this.authConfig.config.headerValuePrefix) {
                        this.authConfig.config.headerValuePrefix = "Bearer";
                    }
                }
                break;
            case types_1.CredentialsMethod.None:
            default:
                break;
        }
    }
    /**
     *
     * @throws {FgaValidationError}
     */
    isValid() {
        const { authConfig } = this;
        switch (authConfig?.method) {
            case types_1.CredentialsMethod.None:
                break;
            case types_1.CredentialsMethod.ApiToken:
                (0, validation_1.assertParamExists)("Credentials", "config.token", authConfig.config?.token);
                (0, validation_1.assertParamExists)("Credentials", "config.headerName", authConfig.config?.headerName);
                (0, validation_1.assertParamExists)("Credentials", "config.headerName", authConfig.config?.headerName);
                break;
            case types_1.CredentialsMethod.ClientCredentials:
                {
                    (0, validation_1.assertParamExists)("Credentials", "config.clientId", authConfig.config?.clientId);
                    (0, validation_1.assertParamExists)("Credentials", "config.apiTokenIssuer", authConfig.config?.apiTokenIssuer);
                    (0, validation_1.assertParamExists)("Credentials", "config.apiAudience", authConfig.config?.apiAudience);
                    (0, validation_1.assertParamExists)("Credentials", "config.clientSecret or config.clientAssertionSigningKey", authConfig.config.clientSecret || authConfig.config.clientAssertionSigningKey);
                    const normalizedApiTokenIssuer = this.normalizeApiTokenIssuer(authConfig.config?.apiTokenIssuer);
                    if (!(0, validation_1.isWellFormedUriString)(normalizedApiTokenIssuer)) {
                        throw new errors_1.FgaValidationError(`Configuration.apiTokenIssuer does not form a valid URI (${normalizedApiTokenIssuer})`);
                    }
                }
                break;
        }
    }
    /**
     * Get access token, request a new one if not cached or expired
     * @return string
     */
    async getAccessTokenHeader() {
        const accessTokenValue = await this.getAccessTokenValue();
        switch (this.authConfig?.method) {
            case types_1.CredentialsMethod.None:
                return;
            case types_1.CredentialsMethod.ApiToken:
                return {
                    name: this.authConfig.config.headerName,
                    value: `${this.authConfig.config.headerValuePrefix ? `${this.authConfig.config.headerValuePrefix} ` : ""}${accessTokenValue}`
                };
            case types_1.CredentialsMethod.ClientCredentials:
                return {
                    name: "Authorization",
                    value: `Bearer ${accessTokenValue}`
                };
        }
    }
    async getAccessTokenValue() {
        switch (this.authConfig?.method) {
            case types_1.CredentialsMethod.None:
                return;
            case types_1.CredentialsMethod.ApiToken:
                return this.authConfig.config.token;
            case types_1.CredentialsMethod.ClientCredentials: {
                const tokenIsValid = !this.accessTokenExpiryDate || (this.accessTokenExpiryDate.getTime() - Date.now() > this.accessTokenExpiryBufferInMs);
                if (this.accessToken && tokenIsValid) {
                    return this.accessToken;
                }
                if (!this.refreshAccessTokenPromise) {
                    this.refreshAccessTokenPromise = this.refreshAccessToken().finally(() => {
                        this.refreshAccessTokenPromise = undefined;
                    });
                }
                return this.refreshAccessTokenPromise;
            }
        }
    }
    /**
     * Normalize API token issuer URL by ensuring it has a scheme
     * @private
     * @param apiTokenIssuer
     * @return string The normalized API token issuer URL
     */
    normalizeApiTokenIssuer(apiTokenIssuer) {
        if (apiTokenIssuer.startsWith(HTTP_SCHEME) || apiTokenIssuer.startsWith(HTTPS_SCHEME)) {
            return apiTokenIssuer;
        }
        return `${HTTPS_SCHEME}${apiTokenIssuer}`;
    }
    /**
     * Constructs the token endpoint URL from the provided API token issuer.
     * @private
     * @param apiTokenIssuer
     * @return string The constructed token endpoint URL if valid, otherwise throws an error
     * @throws {FgaValidationError} If the API token issuer URL is invalid
     */
    buildApiTokenUrl(apiTokenIssuer) {
        const normalizedApiTokenIssuer = this.normalizeApiTokenIssuer(apiTokenIssuer);
        try {
            const url = new URL(normalizedApiTokenIssuer);
            if (!url.pathname || url.pathname.match(/^\/+$/)) {
                url.pathname = `/${exports.DEFAULT_TOKEN_ENDPOINT_PATH}`;
            }
            return url.toString(); // Query params are preserved in the URL
        }
        catch {
            throw new errors_1.FgaValidationError(`Invalid API token issuer URL: ${normalizedApiTokenIssuer}`);
        }
    }
    /**
     * Request new access token
     * @return string
     */
    async refreshAccessToken() {
        const clientCredentials = this.authConfig?.config;
        const url = this.buildApiTokenUrl(clientCredentials.apiTokenIssuer);
        const credentialsPayload = await this.buildClientAuthenticationPayload();
        try {
            const wrappedResponse = await (0, common_1.attemptHttpRequest)({
                url,
                method: "POST",
                data: credentialsPayload,
                headers: {
                    "Content-Type": "application/x-www-form-urlencoded"
                }
            }, {
                maxRetry: 3,
                minWaitInMs: 100,
            }, this.axios);
            const response = wrappedResponse?.response;
            if (response) {
                this.accessToken = response.data.access_token;
                this.accessTokenExpiryDate = new Date(Date.now() + response.data.expires_in * 1000);
                this.accessTokenExpiryBufferInMs = (constants_1.default.TokenExpiryThresholdBufferInSec +
                    (Math.random() * constants_1.default.TokenExpiryJitterInSec)) * 1000;
            }
            if (this.telemetryConfig?.metrics?.counterCredentialsRequest?.attributes) {
                let attributes = {};
                attributes = attributes_1.TelemetryAttributes.fromRequest({
                    userAgent: this.baseOptions?.headers["User-Agent"],
                    fgaMethod: "TokenExchange",
                    url,
                    resendCount: wrappedResponse?.retries,
                    httpMethod: "POST",
                    credentials: clientCredentials,
                    start: performance.now(),
                    attributes,
                });
                attributes = attributes_1.TelemetryAttributes.fromResponse({
                    response,
                    attributes,
                });
                attributes = attributes_1.TelemetryAttributes.prepare(attributes, this.telemetryConfig.metrics?.counterCredentialsRequest?.attributes);
                this.telemetryConfig.recorder.counter(counters_1.TelemetryCounters.credentialsRequest, 1, attributes);
            }
            return this.accessToken;
        }
        catch (err) {
            const authErrorContext = {
                clientId: clientCredentials.clientId,
                audience: clientCredentials.apiAudience,
                grantType: types_1.CredentialsMethod.ClientCredentials,
            };
            if (err instanceof errors_1.FgaApiAuthenticationError) {
                err.clientId = err.clientId ?? authErrorContext.clientId;
                err.audience = err.audience ?? authErrorContext.audience;
                err.grantType = err.grantType ?? authErrorContext.grantType;
                throw err;
            }
            if (err instanceof errors_1.FgaApiError) {
                throw new errors_1.FgaApiAuthenticationError(err, authErrorContext);
            }
            throw err;
        }
    }
    async buildClientAuthenticationPayload() {
        if (this.authConfig?.method !== types_1.CredentialsMethod.ClientCredentials) {
            throw new errors_1.FgaValidationError("Credentials method is not set to ClientCredentials");
        }
        const config = this.authConfig.config;
        if (config.clientAssertionSigningKey) {
            const alg = config.clientAssertionSigningAlgorithm || "RS256";
            const privateKey = await jose.importPKCS8(config.clientAssertionSigningKey, alg);
            const audienceIssuer = this.normalizeApiTokenIssuer(config.apiTokenIssuer);
            const assertion = await new jose.SignJWT({})
                .setProtectedHeader({ alg })
                .setIssuedAt()
                .setSubject(config.clientId)
                .setJti((0, crypto_1.randomUUID)())
                .setIssuer(config.clientId)
                .setAudience(`${audienceIssuer}/`) // Trailing slash is required by the OAuth 2.0 specification
                .setExpirationTime("2m")
                .sign(privateKey);
            return {
                ...config.customClaims,
                client_id: config.clientId,
                client_assertion: assertion,
                audience: config.apiAudience,
                client_assertion_type: "urn:ietf:params:oauth:client-assertion-type:jwt-bearer",
                grant_type: "client_credentials",
            };
        }
        else if (config.clientSecret) {
            return {
                ...config.customClaims,
                client_id: config.clientId,
                client_secret: config.clientSecret,
                audience: config.apiAudience,
                grant_type: "client_credentials",
            };
        }
        throw new errors_1.FgaValidationError("Credentials method is set to ClientCredentials, but no clientSecret or clientAssertionSigningKey is provided");
    }
}
exports.Credentials = Credentials;
//# sourceMappingURL=credentials.js.map