"use strict";
/**
 * JavaScript and Node.js SDK for OpenFGA
 *
 * API version: 1.x
 * Website: https://openfga.dev
 * Documentation: https://openfga.dev/docs
 * Support: https://openfga.dev/community
 * License: [Apache-2.0](https://github.com/openfga/js-sdk/blob/main/LICENSE)
 *
 * NOTE: This file was auto generated by OpenAPI Generator (https://openapi-generator.tech). DO NOT EDIT.
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.CredentialsMethod = void 0;
var CredentialsMethod;
(function (CredentialsMethod) {
    CredentialsMethod["None"] = "none";
    CredentialsMethod["ApiToken"] = "api_token";
    CredentialsMethod["ClientCredentials"] = "client_credentials";
})(CredentialsMethod || (exports.CredentialsMethod = CredentialsMethod = {}));
//# sourceMappingURL=types.js.map